### ISSUE TITLE
NPM not working. npm run start nor npm run deploy. I don't remember changing anything in the code. I just wanted to update my file

### ISSUE THREAD

**Issue by Braillon7** [bradtraversy/modern_portfolio#6]
`PS C:\modern_portfolio> npm run deploy

> modern_portfolio@1.0.0 deploy C:\modern_portfolio
> gh-pages -d dist

error: cannot spawn sh: No such file or directory
fatal: unable to fork

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modern_portfolio@1.0.0 deploy: `gh-pages -d dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modern_portfolio@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\willi\AppData\Roaming\npm-cache\_logs\2018-12-07T01_08_54_886Z-debug.log
PS C:\modern_portfolio>`

**Comment by Braillon7** [comment]
`PS C:\modern_portfolio> npm run start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\willi\AppData\Roaming\npm-cache\_logs\2018-12-07T01_18_16_812Z-debug.log
PS C:\modern_portfolio>`

**Comment by ashirafzal** [comment]
It could be because of your firewall settings

**Comment by sancharid37** [comment]
I have the same Problem what is the solution?

**Comment by sancharid37** [comment]
C:\Users\user\portfolio> npm run sass

> portfolio@1.0.0 sass C:\Users\user\portfolio
> node-sass -w scss/ -o dist/css/ --recursive

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'scss/'
    at Object.lstatSync (fs.js:841:3)
    at Object.module.exports.parseDir (C:\Users\user\portfolio\node_modules\sass-graph\sass-graph.js:153:10)
    at Object.watcher.reset (C:\Users\user\portfolio\node_modules\node-sass\lib\watcher.js:17:21)
    at watch (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:260:20)
    at run (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:319:5)
    at Object.<anonymous> (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:405:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 sass: `node-sass -w scss/ -o dist/css/ --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@1.0.0 sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-02-02T18_39_49_514Z-debug.log

C:\Users\user\portfolio> npm run sass

> portfolio@1.0.0 sass C:\Users\user\portfolio
> node-sass -o css css -w

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'css'
    at Object.lstatSync (fs.js:841:3)
    at Object.module.exports.parseDir (C:\Users\user\portfolio\node_modules\sass-graph\sass-graph.js:153:10)
    at Object.watcher.reset (C:\Users\user\portfolio\node_modules\node-sass\lib\watcher.js:17:21)
    at watch (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:260:20)
    at run (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:319:5)
    at Object.<anonymous> (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:405:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 sass: `node-sass -o css css -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@1.0.0 sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-02-02T18_40_25_854Z-debug.log

C:\Users\user\portfolio> npm run sass

> portfolio@1.0.0 sass C:\Users\user\portfolio
> node-sass -w sass/ -o css/

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'sass/'
    at Object.lstatSync (fs.js:841:3)
    at Object.module.exports.parseDir (C:\Users\user\portfolio\node_modules\sass-graph\sass-graph.js:153:10)
    at Object.watcher.reset (C:\Users\user\portfolio\node_modules\node-sass\lib\watcher.js:17:21)
    at watch (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:260:20)
    at run (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:319:5)
    at Object.<anonymous> (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:405:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 sass: `node-sass -w sass/ -o css/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@1.0.0 sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-02-02T19_21_37_040Z-debug.log

C:\Users\user\portfolio> npm run sass

> portfolio@1.0.0 sass C:\Users\user\portfolio
> node-sass -w scss/ -o dist/css/ --recursive

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'scss/'
    at Object.lstatSync (fs.js:841:3)
    at Object.module.exports.parseDir (C:\Users\user\portfolio\node_modules\sass-graph\sass-graph.js:153:10)
    at Object.watcher.reset (C:\Users\user\portfolio\node_modules\node-sass\lib\watcher.js:17:21)
    at watch (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:260:20)
    at run (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:319:5)
    at Object.<anonymous> (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:405:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@1.0.0 sass: `node-sass -w scss/ -o dist/css/ --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@1.0.0 sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-02-02T19_40_40_474Z-debug.log

**Comment by meetmerchant** [comment]
> C:\Users\user\portfolio> npm run sass
> 
> > portfolio@1.0.0 sass C:\Users\user\portfolio
> > node-sass -w scss/ -o dist/css/ --recursive
> 
> fs.js:115
> throw err;
> ^
> 
> Error: ENOENT: no such file or directory, lstat 'scss/'
> at Object.lstatSync (fs.js:841:3)
> at Object.module.exports.parseDir (C:\Users\user\portfolio\node_modules\sass-graph\sass-graph.js:153:10)
> at Object.watcher.reset (C:\Users\user\portfolio\node_modules\node-sass\lib\watcher.js:17:21)
> at watch (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:260:20)
> at run (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:319:5)
> at Object. (C:\Users\user\portfolio\node_modules\node-sass\bin\node-sass:405:3)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! portfolio@1.0.0 sass: `node-sass -w scss/ -o dist/css/ --recursive`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the portfolio@1.0.0 sass script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\user\AppData\Roaming\npm-cache_logs\2019-02-02T18_39_49_514Z-debug.log

Hey Im getting the same error, whats the solution? Could you solve it?
